from project.decoration.decoration_repository import DecorationRepository
from project.decoration.ornament import Ornament
from project.decoration.plant import Plant
from project.fish.freshwater_fish import FreshwaterFish
from project.fish.saltwater_fish import SaltwaterFish
from project.aquarium.freshwater_aquarium import FreshwaterAquarium
from project.aquarium.saltwater_aquarium import SaltwaterAquarium
from project.controller import Controller


orn = Ornament()
plant = Plant()
orn_2 = Ornament()
# print(orn.__dict__)
# print(plant.__dict__)

dec_rep = DecorationRepository()
dec_rep.add(orn)
dec_rep.add(orn_2)
dec_rep.add(plant)
print(dec_rep.find_by_type("Ornament"))
print(dec_rep.__dict__)
dec_rep.remove(orn_2)
dec_rep.remove(orn_2)

fresh_water_fish = FreshwaterFish("Sladka", "Freshwater", 5.5)
salt_water_fish = SaltwaterFish("Salty", "Saltwater", 8.4)
fresh_water_fish_2 = FreshwaterFish("Freshy2", "FreshFish2", 7)
salt_water_fish_2 = SaltwaterFish("Salty_2", "Saltwater", 4)
fresh_aquarium = FreshwaterAquarium("FreshShitAquarium")
salt_aquarium = SaltwaterAquarium("SaltwaterShitAquarium")
print(fresh_aquarium.add_fish(fresh_water_fish))
fresh_aquarium.add_fish(salt_water_fish)
print(fresh_aquarium.add_fish(fresh_water_fish_2))
salt_aquarium.add_fish(salt_water_fish)
salt_aquarium.add_fish(salt_water_fish_2)
salt_aquarium.remove_fish(salt_water_fish_2)
salt_aquarium.add_decoration(orn)
salt_aquarium.add_decoration(plant)
print(salt_aquarium.__dict__)
fresh_water_fish.eat()
salt_water_fish.eat()
salt_aquarium.feed()
fresh_aquarium.add_decoration(orn)
fresh_aquarium.add_decoration(orn_2)
fresh_aquarium.remove_fish(fresh_water_fish)
fresh_aquarium.remove_fish(fresh_water_fish_2)
print(salt_aquarium.__str__())
print(fresh_aquarium.__str__())

controller_one = Controller()
print(controller_one.add_aquarium("SaltwaterAquarium", "SaltBaeAquarium"))
print(controller_one.add_aquarium("FreshwaterAquarium", "FreshPrinceAquarium"))
print(controller_one.add_aquarium("SomeTypeofAquarium", "Some"))
controller_one.add_aquarium("FreshwaterAquarium", "Number 3")
print(controller_one.aquariums)
print(controller_one.add_decoration("Ornament"))
controller_one.add_decoration("Ornament")
controller_one.add_decoration("Plant")
print(controller_one.decorations_repository.decorations)
print(controller_one.insert_decoration("FreshPrinceAquarium", "Ornament"))
print(controller_one.insert_decoration("FreshPrinceAquarium", "KraKra"))
controller_one.insert_decoration("FreshPrinceAquarium", "Plant")
print(controller_one.insert_decoration("FreshPrinceAquarium", "Plant"))
print(controller_one.add_fish("FreshPrinceAquarium", "Freshwater", "Jelly", "Name", 4.44))
print(controller_one.add_fish("FreshPrinceAquarium", "SaltwaterFish", "Jellyfish", "FreshName", 4.44))
print(controller_one.add_fish("FreshPrinceAquarium", "FreshwaterFish", "Shark", "Samantha", 23.0))
print(controller_one.add_fish("FreshPrinceAquarium", "FreshwaterFish", "Tuna", "Shits", 6.0))
print(controller_one.add_fish("FreshPrinceAquarium", "FreshwaterFish", "Sloppy", "Manic", 6.0))
print(controller_one.feed_fish("FreshPrinceAquarium"))
print(controller_one.calculate_value("FreshPrinceAquarium"))
print(controller_one.report())
print(controller_one.calculate_value("SomeTypeofAquarium"))
controller_one.add_decoration("Ornament")
controller_one.add_decoration("Plant")
print(controller_one.add_fish("SaltBaeAquarium", "SaltwaterFish", "Jellyfish", "FreshName", 4.44))
controller_one.insert_decoration("SaltBaeAquarium", "Plant")
controller_one.insert_decoration("SaltBaeAquarium", "Ornament")
print(controller_one.calculate_value("SaltBaeAquarium"))
